### ISSUE TITLE
Polar vector input node

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#11]
Inputs: spherical or cylindrical coordinates. Output: vectors.
May be useful, for example, for archimedian and logariphmic spirals.

**Comment by portnov** [comment]
Illustrations:
![helix](https://cloud.githubusercontent.com/assets/284644/5840890/917b2ae0-a1ba-11e4-9432-33b68d8a19e3.png)
![logariphmic](https://cloud.githubusercontent.com/assets/284644/5840891/917fddf6-a1ba-11e4-9cd1-a3b354a46348.png)
![archimedian](https://cloud.githubusercontent.com/assets/284644/5840892/91800812-a1ba-11e4-84b3-c9347ed1b397.png)

**Comment by portnov** [comment]
![spherical](https://cloud.githubusercontent.com/assets/284644/5840984/2e5bd24c-a1bb-11e4-97b3-99864881fa69.png)

**Comment by portnov** [comment]
![box](https://cloud.githubusercontent.com/assets/284644/5841825/d0c494aa-a1c1-11e4-9c36-4c94076ba8d7.png)

**Comment by nortikin** [comment]
in old todo list even forgot to implement
