### ISSUE TITLE
Bricks generator

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#19]
Generate a brick-like mesh. See parameters of Brick procedural texture as example; also see Floor Generator addon.

**Comment by portnov** [comment]
![2](https://cloud.githubusercontent.com/assets/284644/5963534/0b561d5c-a80f-11e4-88a7-f5f54a277c81.png)
![1](https://cloud.githubusercontent.com/assets/284644/5981635/a75e5a74-a8dd-11e4-9d1f-64e19da8f01a.png)

**Comment by portnov** [comment]
![3](https://cloud.githubusercontent.com/assets/284644/5981642/bb7ceda4-a8dd-11e4-9319-c9728199d44e.png)
![5](https://cloud.githubusercontent.com/assets/284644/5981643/bb85d572-a8dd-11e4-88c0-ebd018bfcdd1.png)

**Comment by portnov** [comment]
![negative-toothing](https://cloud.githubusercontent.com/assets/284644/5977166/125a84d2-a8b7-11e4-86a9-de6fc8a4c8e2.png)

**Comment by portnov** [comment]
![6](https://cloud.githubusercontent.com/assets/284644/5978070/d5c15412-a8be-11e4-987e-bfd6aa3e148a.png)

![hex-building1](https://cloud.githubusercontent.com/assets/284644/5978008/4771c6ec-a8be-11e4-9da5-896d92402e52.png)

**Comment by portnov** [comment]
![8](https://cloud.githubusercontent.com/assets/284644/5981672/0693c66e-a8de-11e4-8326-a75a15e37e74.png)
![7](https://cloud.githubusercontent.com/assets/284644/5981673/06e0c5fe-a8de-11e4-822f-b1b44681982c.png)

**Comment by portnov** [comment]
![4](https://cloud.githubusercontent.com/assets/284644/5981695/2fd5badc-a8de-11e4-858e-10ce590b19ec.png)

**Comment by portnov** [comment]
![triangles1](https://cloud.githubusercontent.com/assets/284644/5987267/f03949f6-a942-11e4-8029-4713de295f90.png)

**Comment by nortikin** [comment]
cool. missed this node
