### ISSUE TITLE
Mesh filter

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#21]
Given a set of vertices, edges and faces, filter:
- Vertices: wire, boundary, interior vertices; and edges and faces which connect selected vertices.
- Edges: wire, boundary, interior, convex, concave, contiguous.
- Faces: boundary (which have any edge boundary) and interior (all others).

**Comment by portnov** [comment]
![3](https://cloud.githubusercontent.com/assets/284644/6081558/53b7ea70-ae3c-11e4-9c32-b147be11af5b.png)
![1](https://cloud.githubusercontent.com/assets/284644/6081560/53eea0f6-ae3c-11e4-889c-f60441accc1d.png)
![2](https://cloud.githubusercontent.com/assets/284644/6081559/53ed9486-ae3c-11e4-8fbc-82f7e8029434.png)

**Comment by portnov** [comment]
TODO: mask outputs for vertices and edges modes.

**Comment by nortikin** [comment]
and main question. is it list function or modifier?
if it is list, so as mask has to have in and out coresponding nodes?

**Comment by portnov** [comment]
It is a "filter" of lists of vertices, edges and faces. Mask outputs can be used with usual List Mask In node, as shown at first screen above, for example.
