### ISSUE TITLE
`Extrude edges only' node

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#23]
See http://www.blender.org/api/blender_python_api_2_72_1/bmesh.ops.html#bmesh.ops.extrude_edge_only

**Comment by portnov** [comment]
![2](https://cloud.githubusercontent.com/assets/284644/6318598/6eb0c3ba-babc-11e4-8cab-ccb2d4fe39a9.png)
![1](https://cloud.githubusercontent.com/assets/284644/6318599/6ee0d474-babc-11e4-8d3a-f9f86963bf10.png)

**Comment by portnov** [comment]
done.

**Comment by nortikin** [comment]
maybe it should be part of extrude node to limit divercity of nodes, that makes some disorder at the end. Please.

**Comment by portnov** [comment]
In fact there are three different operations:
- Extrude separate faces
- Extrude region of faces
- Extrude edges.

It is possible to do one node for all three operations with different modes...
