### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#24]

**Comment by portnov** [comment]
![rightmost](https://cloud.githubusercontent.com/assets/284644/23761326/aa0cacf6-051c-11e7-8dae-1848bc0e81cd.png)

![looking-right](https://cloud.githubusercontent.com/assets/284644/23761372/cc0950b6-051c-11e7-9c57-4b76a91c2e5d.png)

**Comment by portnov** [comment]
![by-sphere](https://cloud.githubusercontent.com/assets/284644/23761537/5106db9e-051d-11e7-81e8-2fca30c02b18.png)

**Comment by portnov** [comment]
![cube_normal](https://cloud.githubusercontent.com/assets/284644/23824189/4686ba06-069c-11e7-9522-51d25e7667ad.png)
![cube_matrix](https://cloud.githubusercontent.com/assets/284644/23824190/46b7b1a6-069c-11e7-87fb-ddabeb87e6b9.png)

**Comment by portnov** [comment]
![normal-outside](https://cloud.githubusercontent.com/assets/284644/23831238/9d9bbf0c-0747-11e7-9a3f-8706b3ff1e7d.png)
![edge_dir](https://cloud.githubusercontent.com/assets/284644/23831239/9d9c5ac0-0747-11e7-8661-921c3304fb41.png)
![edge_dir2](https://cloud.githubusercontent.com/assets/284644/23831240/9d9cd59a-0747-11e7-8765-e89b00f5c081.png)

**Comment by portnov** [comment]
![normal-outside-2](https://cloud.githubusercontent.com/assets/284644/23831280/62e48816-0748-11e7-887f-b9223dbbf939.png)

**Comment by portnov** [comment]
![edge-dir-bevel](https://cloud.githubusercontent.com/assets/284644/23831501/fcebffee-074c-11e7-8e15-de759d67588c.png)

**Comment by portnov** [comment]
![plane-to-circle](https://cloud.githubusercontent.com/assets/284644/23907622/f0112550-08fb-11e7-9a3e-291fc4944d7d.png)
![box-to-two-points](https://cloud.githubusercontent.com/assets/284644/23907624/f045fb4a-08fb-11e7-85cf-b78e664f451c.png)
![torus-to-line](https://cloud.githubusercontent.com/assets/284644/23907626/f047c2ae-08fb-11e7-99b8-d630eaea2cad.png)
![sphere-to-plane](https://cloud.githubusercontent.com/assets/284644/23907625/f046ab76-08fb-11e7-9172-42f17f4a4146.png)
![plane-to-point](https://cloud.githubusercontent.com/assets/284644/23907623/f045eab0-08fb-11e7-8cf4-130a34a258dc.png)
![plane-extrude](https://cloud.githubusercontent.com/assets/284644/23907627/f04f217a-08fb-11e7-97c5-b2702598b3f7.png)

**Comment by nortikin** [comment]
Selector!

**Comment by portnov** [comment]
![plane](https://cloud.githubusercontent.com/assets/284644/24079413/a2757a08-0cb1-11e7-9ef5-155c888b38dd.png)

**Comment by portnov** [comment]
![habo](https://cloud.githubusercontent.com/assets/284644/24079457/a47553ae-0cb2-11e7-9b25-096cdf88a4a1.png)

**Comment by portnov** [comment]
![clamp-on](https://cloud.githubusercontent.com/assets/284644/24082404/3b509fe0-0cef-11e7-879e-6770df9a2649.png)
![clamp-off](https://cloud.githubusercontent.com/assets/284644/24082405/3b84b186-0cef-11e7-94d6-c58d4fcd62e9.png)

**Comment by portnov** [comment]
![bbox](https://cloud.githubusercontent.com/assets/284644/24332028/248a1026-1261-11e7-8886-f7a0f88ecb60.png)

**Comment by portnov** [comment]
![bend](https://cloud.githubusercontent.com/assets/284644/24372062/9cb51d1e-134e-11e7-8c23-bc7d12768606.png)
![twist](https://cloud.githubusercontent.com/assets/284644/24372066/9ce9b2d6-134e-11e7-9652-4ce697498bfd.png)
![taper](https://cloud.githubusercontent.com/assets/284644/24372065/9ce6e452-134e-11e7-9313-eba01bbc3542.png)

**Comment by portnov** [comment]
![face_normal](https://cloud.githubusercontent.com/assets/284644/25073036/6cabd4da-22ff-11e7-9880-143d8af4b8c9.png)
![face_area](https://cloud.githubusercontent.com/assets/284644/25073037/6ce11f50-22ff-11e7-8744-f5aefb616f23.png)
![edge_direction](https://cloud.githubusercontent.com/assets/284644/25073038/6ce16c26-22ff-11e7-8d79-b9e3cb825183.png)

**Comment by portnov** [comment]
![Screenshot_20200122_210432](https://user-images.githubusercontent.com/284644/72911065-43fa0b00-3d5b-11ea-84b9-ea1f3df6f84a.png)

**Comment by portnov** [comment]
![Screenshot_20200428_204912](https://user-images.githubusercontent.com/284644/80508641-bcdbb500-8991-11ea-9ed0-030ca6d0bc44.png)

**Comment by portnov** [comment]
![Screenshot_20200510_130635](https://user-images.githubusercontent.com/284644/81494064-31322480-92bf-11ea-82eb-910a71ccc78a.png)

**Comment by portnov** [comment]
![Screenshot_20200510_210641](https://user-images.githubusercontent.com/284644/81504481-f2be5900-9302-11ea-8948-fb189c3fc3c5.png)
![Screenshot_20200510_205625](https://user-images.githubusercontent.com/284644/81504488-f94cd080-9302-11ea-9da5-f27f633f2191.png)

**Comment by portnov** [comment]
![Screenshot_20200510_235126](https://user-images.githubusercontent.com/284644/81508399-5eadbb00-931d-11ea-902c-bea4649ad9d7.png)
![Screenshot_20200510_235429](https://user-images.githubusercontent.com/284644/81508400-5f465180-931d-11ea-9ce7-95b69c2e4925.png)

**Comment by portnov** [comment]
Vectorization 2 - Sizes & radius per rectangle:
![Screenshot_20200511_011252](https://user-images.githubusercontent.com/284644/81509502-9c621200-9324-11ea-92a7-4d3d46f01c7e.png)

**Comment by portnov** [comment]
Vectorization 1 - sizes only:
![Screenshot_20200511_010821](https://user-images.githubusercontent.com/284644/81509449-3d040200-9324-11ea-9b31-504633b880b4.png)

**Comment by portnov** [comment]
Vectorization 3 - sizes & radius per corner:

![Screenshot_20200511_011020](https://user-images.githubusercontent.com/284644/81509473-60c74800-9324-11ea-8c92-48b3d427727d.png)

**Comment by portnov** [comment]
![Screenshot_20200512_215124](https://user-images.githubusercontent.com/284644/81722582-03a1d280-949b-11ea-8e99-9d9354f5e906.png)
![Screenshot_20200512_215218](https://user-images.githubusercontent.com/284644/81722585-056b9600-949b-11ea-9ad9-01f7093c9c80.png)
![Screenshot_20200512_215315](https://user-images.githubusercontent.com/284644/81722587-06042c80-949b-11ea-81a4-43d134c9ca77.png)

**Comment by portnov** [comment]
![Screenshot_20200523_124440](https://user-images.githubusercontent.com/284644/82756581-79d7fa80-9df4-11ea-9819-25616fd23aca.png)
![Screenshot_20200523_125015](https://user-images.githubusercontent.com/284644/82756583-7ba1be00-9df4-11ea-9048-3be46c6b85fe.png)
![Screenshot_20200523_232339](https://user-images.githubusercontent.com/284644/82756586-7c3a5480-9df4-11ea-964b-91ad5b9ecd69.png)
![Screenshot_20200523_235053](https://user-images.githubusercontent.com/284644/82756587-7cd2eb00-9df4-11ea-8bfc-bb704eef33e0.png)
![Screenshot_20200524_132722](https://user-images.githubusercontent.com/284644/82756588-7d6b8180-9df4-11ea-925e-1628a4413bf9.png)

**Comment by portnov** [comment]
![Screenshot_20200524_195340](https://user-images.githubusercontent.com/284644/82757214-56af4a00-9df8-11ea-923e-65b1677f3d39.png)

**Comment by portnov** [comment]
![Screenshot_20200524_234248](https://user-images.githubusercontent.com/284644/82762154-dd741f00-9e18-11ea-875b-ed3a59c3b76c.png)
![Screenshot_20200524_234403](https://user-images.githubusercontent.com/284644/82762156-df3de280-9e18-11ea-96a9-695476bf6fdc.png)
![Screenshot_20200524_234546](https://user-images.githubusercontent.com/284644/82762157-df3de280-9e18-11ea-987a-15eeb02c8bac.png)
![Screenshot_20200524_234635](https://user-images.githubusercontent.com/284644/82762158-dfd67900-9e18-11ea-9f52-98374c7605df.png)

**Comment by portnov** [comment]
![Screenshot_20200525_003017](https://user-images.githubusercontent.com/284644/82763139-eb2ca300-9e1e-11ea-9e21-a11232adc29c.png)

**Comment by portnov** [comment]
![Screenshot_20200524_220114](https://user-images.githubusercontent.com/284644/82763274-e74d5080-9e1f-11ea-8c7b-d5f020abc04f.png)

**Comment by portnov** [comment]
![Screenshot_20200525_005039](https://user-images.githubusercontent.com/284644/82763513-c423a080-9e21-11ea-9e25-38847a6fa464.png)

**Comment by portnov** [comment]
![Screenshot_20200530_131400](https://user-images.githubusercontent.com/284644/83325996-3533df80-a28a-11ea-9e72-7e4c46fa4097.png)
![Screenshot_20200530_131537](https://user-images.githubusercontent.com/284644/83325998-36fda300-a28a-11ea-88a4-abbe05f10a7a.png)
![Screenshot_20200530_132013](https://user-images.githubusercontent.com/284644/83325999-38c76680-a28a-11ea-84c5-bab8f21660d3.png)
![Screenshot_20200530_135728](https://user-images.githubusercontent.com/284644/83326002-3a912a00-a28a-11ea-8881-183a60b84e72.png)

![Screenshot_20200530_171910](https://user-images.githubusercontent.com/284644/83328036-bc3c8400-a299-11ea-9b33-0e6fe2c7fd36.png)

![Screenshot_20200530_172732](https://user-images.githubusercontent.com/284644/83328220-e6db0c80-a29a-11ea-9997-ebd3affd43eb.png)

**Comment by portnov** [comment]
![Screenshot_20200531_220215](https://user-images.githubusercontent.com/284644/83358400-a8257f00-a38c-11ea-88ba-530ccc1742fd.png)
![Screenshot_20200531_220358](https://user-images.githubusercontent.com/284644/83358403-a956ac00-a38c-11ea-9619-00af2e93b613.png)

**Comment by portnov** [comment]
![Screenshot_20200610_204841](https://user-images.githubusercontent.com/284644/84289369-d6107d80-ab5b-11ea-909f-62a9c9205de2.png)

**Comment by portnov** [comment]
![Screenshot_20200610_205319](https://user-images.githubusercontent.com/284644/84289874-7666a200-ab5c-11ea-8483-c7b885cab805.png)

**Comment by portnov** [comment]
![Screenshot_20200613_134244](https://user-images.githubusercontent.com/284644/84564568-07679400-ad7c-11ea-8370-c4a8008a8c74.png)

**Comment by portnov** [comment]
![Screenshot_20200616_233936](https://user-images.githubusercontent.com/284644/84814573-1e7fdd80-b02b-11ea-82d9-572288d7a770.png)

**Comment by portnov** [comment]
![Screenshot_20200617_184718](https://user-images.githubusercontent.com/284644/84906631-a4536580-b0cb-11ea-83b7-5a9920757554.png)
![Screenshot_20200617_185131](https://user-images.githubusercontent.com/284644/84906638-a5849280-b0cb-11ea-98a7-aad8803bfb9d.png)

**Comment by portnov** [comment]
![Screenshot_20200624_154930](https://user-images.githubusercontent.com/284644/85555664-922f7500-b63f-11ea-8479-9ee8db89ee11.png)

**Comment by portnov** [comment]
![Screenshot_20200624_172505](https://user-images.githubusercontent.com/284644/85555750-a8d5cc00-b63f-11ea-8f28-3565e3a8d1e4.png)

**Comment by portnov** [comment]
![Screenshot_20200624_222156](https://user-images.githubusercontent.com/284644/85607132-3da2ee80-b66d-11ea-9c8b-2e730dd97751.png)

**Comment by portnov** [comment]
![Screenshot_20200624_230223](https://user-images.githubusercontent.com/284644/85608724-c79f8700-b66e-11ea-97f8-5b54e9d90401.png)

**Comment by portnov** [comment]
![Screenshot_20200626_193257](https://user-images.githubusercontent.com/284644/85880809-14619a00-b7f6-11ea-9aa4-1e03e604fda8.png)
![Screenshot_20200626_204115](https://user-images.githubusercontent.com/284644/85880815-162b5d80-b7f6-11ea-98ec-3def49c4381c.png)
