### ISSUE TITLE
Duplicate mesh along edges

### ISSUE THREAD

**Issue by portnov** [portnov/sverchok#6]
Given two vertices V1,V2 and a set of meshes (i.e. vertices, edges and faces), produce an array of meshes aligned, scaled and placed along segment V1-V2. There should be options:
- How to determine count of objects in array. Options: a) count is specified by user; meshes are scaled up or down as neccessary; b) count is determined automatically from distance from V1 to V2 and size of input mesh, and meshes are scaled only up (for example, if donor mesh is 1 unit long, and V1-V2 is 3.6 units, then there should be 3 meshes scaled to be 1.2 units long each); c) the same as b, but meshes are scaled only down; d) the same, but meshes are not scaled, so some empty space will be left between meshes.
- When scaling meshes, scale them only along one axis or along all axes.
- Which axis of donor object to align with direction of V1-V2 (X,Y or Z).
- It should be possible to use this as post-processor for prepared meshes; for example, given a Box, put 10 small spheres along each of it's edges. For this, there should be an option how to input vertices V1 and V2: a) have two inputs for two vertices; b) have one inputs for vertices of recipient mesh, and one input for edges of it; process each edge.

**Comment by portnov** [comment]
![1](https://cloud.githubusercontent.com/assets/284644/5704175/baf816c0-9a90-11e4-9d27-23cac9e0689c.png)

Currently it lacks most of options, but it works somehow.

**Comment by portnov** [comment]
![2](https://cloud.githubusercontent.com/assets/284644/5709138/07cd4b50-9ab9-11e4-9473-015a111aba69.png)
Current state.

**Comment by portnov** [comment]
1. Since I anyway calculate matrices for applying to generated objects, why not output these matrices for later usage in other nodes? So I added "matrices" output.
2. Since I have "matrices" output, it is possible to apply these matrices to generated objects in another node, in "Matrix Apply" for example.
3. But I think in most cases it will be simpler to apply matrices in single node. So I added an option: whether to apply matrices or not.
4. This also opened an interesting possibility to apply generated matrices not to generated objects, but to something different.
   Have no idea if it will be usefull or not, but decided to better have this feature than not.
   Illustration:
   ![3](https://cloud.githubusercontent.com/assets/284644/5709612/23b4626e-9abd-11e4-8a80-24400ab1d128.png)
   Here vertices of Box are used only to generate series of matrices, which would be applied if I wanted to align duplicated Boxes along given edge. But, say, i decided to align not that boxes but Circles, of another size.

**Comment by ly29** [comment]
@portnov 
It is an interesting addition, we have some slightly different ideas about its interfaces.
Using the edge normal of a mesh with faces would provide an interesting option for alignment in 3d

**Comment by portnov** [comment]
@ly29, i found a bit odd bug: sometimes generated meshes have normals pointing inside. I think it's a result of complex matrices manipulation. I wonder, will it worth to use bpy.mesh.ops.normals_make_consistent to fix it? Currently i do not use bpy.mesh...

**Comment by ly29** [comment]
Make it an optional step if affects performance, also use the bmesh module instead of `bpy.ops`.
It is wort to think about, if nothing else that should probably also be available as separate node. And mesh socket.

**Comment by portnov** [comment]
For now, i discovered that not only normals were flipped - whole objects were, due to bug in matrices calculation. It seems i fixed it for now.

**Comment by portnov** [comment]
![4](https://cloud.githubusercontent.com/assets/284644/5724154/86f006ae-9b6b-11e4-976e-ccec3ff20c16.png)

**Comment by portnov** [comment]
![7](https://cloud.githubusercontent.com/assets/284644/5741267/e8dd73f4-9c2b-11e4-969f-b9b5b6b8e211.png)

And the same with Padding = 0.04:

![8](https://cloud.githubusercontent.com/assets/284644/5741274/f0c28e88-9c2b-11e4-9b8f-1fd7d6b22a57.png)

**Comment by zeffii** [comment]
padding is very useful feature

**Comment by portnov** [comment]
Iterate + Duplicate:

![9](https://cloud.githubusercontent.com/assets/284644/5741989/b17ca164-9c30-11e4-99f5-055afc3825d3.png)

**Comment by portnov** [comment]
![iterate_plus_duplicate](https://cloud.githubusercontent.com/assets/284644/5745657/2eb9e252-9c4c-11e4-94b0-790aee92419d.png)
The same plus Offset plus Solidify.

**Comment by ly29** [comment]
very nice

**Comment by zeffii** [comment]
yep, like the render effect, is it freestyle with AO ?

**Comment by portnov** [comment]
Yes.

**Comment by nortikin** [comment]
ыыы
have no words to express impression

**Comment by portnov** [comment]
I consider this done. Available currently in master as "Duplicate objects along edge" in "Beta" section.

**Comment by portnov** [comment]
http://www.youtube.com/watch?v=xtzgXcDSJZs&feature=youtu.be - here this node is used to automatically adjust number of pillows on sofa. Just a quick demo.

**Comment by portnov** [comment]
![house3](https://cloud.githubusercontent.com/assets/284644/5805880/239454b0-a035-11e4-91e7-f4c6cea0a42d.png)
Profile node + Duplicate along edges + Cross-sections.

**Comment by stansu** [comment]
can i use different donor?
like RailClone?
https://www.itoosoft.com/railclone.php
